### ISSUE TITLE
Enlarge the widget

### ISSUE THREAD

**Issue by lmacken** [fedora-infra/apps.fp.o#30]
Things are looking pretty cramped these days, and it's not as user-friendly as it used to be.

I tried tweaking some of the CSS a couple of weeks ago, but I couldn't figure it out. :confused:

**Comment by ralphbean** [comment]
Yeah, the text is super crowded.  Agreed.

**Comment by lmacken** [comment]
Or, is apps.fp.o potentially obsoleted by https://github.com/fedora-infra/fedmenu :grey_question:

**Comment by ralphbean** [comment]
> is apps.fp.o potentially obsoleted

Could be... but I like still having the landing page for people who get there accidentally.  :)

**Comment by lmacken** [comment]
Ah, true. :ocean: :boat:

**Comment by ralphbean** [comment]
This might be useful:  http://stackoverflow.com/questions/4938346/canvas-width-and-height-in-html5

**Comment by ralphbean** [comment]
More specific:  http://stackoverflow.com/questions/10109065/resize-canvas-for-jit-graph-library-on-window-resize
